name: Build production binary

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Настройка Ruby
        uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
        with:
          ruby-version: '3.1.0'
      - name: Установка зависимостей
        run: gem install 'colorize'
      - name: Установка ocra2
        run: gem install ocra2
      - name: Сборка .exe
        run: ocra ./KeyBox/source.rb --output keybox.exe --add-all-core --no-dep-run --gem-full --chdir-first
